version: '3'
services:
    php:
        build:
            context: .
            dockerfile: DockerFile
        volumes:
            - './:/var/www'
    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - './:/var/www/'
            - './docker/nginx/conf.d:/etc/nginx/conf.d'
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
